SELECT
    id,
    symbol,
    name,
    image,
    current_price,
    market_cap,
    market_cap_rank,
    total_volume,
    high_24h,
    low_24h,
    price_change_percentage_24h,
    price_change_percentage_7d_in_currency  AS price_change_pct_7d,
    price_change_percentage_30d_in_currency AS price_change_pct_30d,
    circulating_supply,
    total_supply,
    max_supply,
    last_updated::TIMESTAMP AS last_updated,
    ingested_at
FROM read_parquet('../../data/bronze/*.parquet')